default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: noticias_development

test:
  <<: *default
  database: noticias_test

production:
  <<: *default
  database: noticias_production
  username: noticias
  password: <%= ENV['NOTICIAS_DATABASE_PASSWORD'] %>
